log_dir: /home/gensyn/shared/test

game_manager:
  _target_: genrl_swarm.game.BaseGameManager
  max_stage: 3
  max_round: 1
  prune_K: 5
  game_state: 
    round: 0
    stage: 0
    swarm_size: 1
    rank: 0    
  reward_manager:
    _target_: genrl_swarm.rewards.DefaultRewardManager
    reward_fn_store:
      _target_: genrl_swarm.rewards.reward_store.RewardFnStore
      max_rounds: 1
      reward_fn_stores:
        - _target_: genrl_swarm.rewards.reward_store.RoundRewardFnStore
          num_stages: 3
          reward_fns:
            - _target_: hydra.utils.get_method
              path: genrl_swarm.examples.gsm8k.stage1_rewards.top_k_cumulative_reward
            - _target_: hydra.utils.get_method
              path: genrl_swarm.examples.gsm8k.stage2_rewards.top_k_cumulative_reward
            - _target_: hydra.utils.get_method
              path: genrl_swarm.examples.gsm8k.stage2_rewards.top_k_cumulative_reward
  trainer:
    _target_: genrl_swarm.examples.gsm8k.trainer.GRPOTrainerModule
    models:
      - _target_: transformers.AutoModelForCausalLM.from_pretrained
        pretrained_model_name_or_path: Gensyn/Qwen2.5-0.5B-Instruct
        config: trl.trainer.GRPOConfig
  data_manager:
    _target_: genrl_swarm.examples.gsm8k.data.GSM8KDataManager
    # num_students_to_sample, num_critics_to_sample, subsampling_method, prompt_generator_role use defaults
  run_mode: "Train"